# Generated by Django 3.0.7 on 2020-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('duration', models.FloatField()),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('genres', models.ManyToManyField(related_name='films', to='genres.Genre')),
            ],
        ),
    ]
